spring.application.name=reactApi
server.port=8199


#KAFKA주소
spring.kafka.bootstrap-servers=localhost:9092

#보내는 셋팅
#key : value로 보낸다는 설정
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#모든 패키지 허용
spring.kafka.producer.properties.spring.json.trusted.packages=*


#consumer 받는 셋팅
spring.kafka.consumer.group-id=test-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.Map

#producer 5초간 반응 없으면 타임아웃
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.request.timeout.max.ms=5000

#consumer 재시도 간격
spring.kafka.consumer.properties.reconnect.backoff.ms=5000
spring.kafka.consumer.properties.reconnect.backoff.max.ms=20000
